export const BLOG_TITLES: string[] = [
  "Cabinet Refacing vs Replacement: Cost, Timeline, and Mess Compared",
  "How Long Cabinet Refacing Takes in Arizona Homes",
  "How Much Cabinet Refacing Costs in Phoenix and the Valley",
  "What Cabinet Refacing Includes (And What It Doesn’t)",
  "Is Cabinet Refacing Worth It for Older Arizona Homes",
  "Cabinet Refacing for Kitchens and Bathrooms: What to Expect",
  "Common Myths About Cabinet Refacing (Debunked)",
  "Signs Your Cabinets Are Good Candidates for Refacing",
  "Best Cabinet Materials for Arizona Heat and Sun Exposure",
  "Cabinet Refacing Options That Hold Up in Desert Climates",
  "Is Cabinet Refacing HOA-Approved in Arizona Communities",
  "Kitchen Upgrades That Don’t Require Permits in Arizona",
  "Cabinet Refacing for Seasonal Arizona Homes and Snowbirds",
  "How Cabinet Refacing Handles Arizona Dust, Heat, and UV",
  "Cabinet Refacing for Ranch-Style and Southwestern Homes",
  "Popular Cabinet Door Styles for Arizona Kitchens",
  "Shaker vs Slab Cabinet Doors: Which Is Right for Your Home",
  "Best Cabinet Colors for Bright Arizona Kitchens",
  "How to Choose Cabinet Hardware That Matches Your Home",
  "Cabinet Refacing Ideas for Small Kitchens",
  "Timeless Cabinet Styles That Don’t Go Out of Trend",
  "Mixing Cabinet Colors: What Works and What Doesn’t",
  "How Cabinet Refacing Changes the Look of a Kitchen",
  "The Step-by-Step Cabinet Refacing Process Explained",
  "What Happens During a Cabinet Refacing Installation",
  "How to Prepare Your Kitchen for Cabinet Refacing",
  "How Long Cabinets Last After Refacing",
  "Cabinet Refacing vs Painting: Key Differences",
  "Questions to Ask Before Choosing a Cabinet Refacing Company",
  "How Cabinet Refacing Improves Home Value",
  "Cabinet Refacing for Homeowners Planning to Sell",
  "Cabinet Refacing in Phoenix: What Homeowners Should Know",
  "Cabinet Refacing in the East Valley: Cost and Timeline",
  "Cabinet Refacing in the West Valley: What to Expect",
  "Cabinet Refacing for Scottsdale and North Phoenix Homes",
  "Cabinet Refacing for Newer Arizona Subdivisions",
  "Cabinet Refacing for Historic and Older Phoenix Homes",
  "Why Vulpine Homes Focuses on Refacing Instead of Full Replacement",
  "The Vulpine Homes Approach to Cabinet Refacing",
  "How the Vulpine Visualizer Helps Homeowners Plan Refacing",
  "What Makes Vulpine Homes Different From Big-Box Remodelers",
  "How Fast Cabinet Refacing Fits Busy Homeowner Schedules",
  "Clean Kitchen Upgrades: Why Refacing Is a Low-Disruption Option",
  "Cabinet Refacing and Soft-Close Hardware: Is It Worth It",
  "Cabinet Refacing for Rental Properties and Investment Homes",
  "How Cabinet Refacing Works With Existing Countertops",
  "Cabinet Refacing for Homes With Open-Concept Kitchens",
  "Cabinet Refacing Before and After: What Actually Changes",
  "How to Maintain Cabinets After Refacing",
  "When Cabinet Refacing Is Better Than a Full Remodel",
];
